before:
  hooks:
    - go mod download
builds:
  -
    goos: [darwin]
    goarch: [amd64]
archives:
  - wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  name: totp-keychain
  github:
    owner: moul
    name: homebrew-moul
  commit_author:
    name: moul-bot
    email: "m+bot@42.am"
  homepage: https://manfred.life/cryptography
  description: TOTP cli backed by the OS X keychain
